databases:
  - name: assetsmanagement
    databaseName: assets_management
    user: harishkumar

services:
  - type: web
    name: assetsmanagement
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn assetsmanagement.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: assets_management
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
