# Generated by Django 4.1.3 on 2022-12-07 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assets', '0002_remove_asset_id_alter_asset_serial_number'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(max_length=100)),
                ('status', models.CharField(choices=[('GRANTED', 'Granted'), ('DENIED', 'Denied'), ('PENDING', 'Pending')], default='PENDING', max_length=10)),
                ('asset_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets.asset')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.employee')),
            ],
        ),
    ]
