# Generated by Django 4.1.3 on 2022-12-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=10)),
                ('refresh_Token', models.CharField(max_length=800)),
                ('access_Token', models.CharField(max_length=800)),
            ],
        ),
    ]
