# Generated by Django 4.1.3 on 2022-11-27 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_name', models.CharField(max_length=20)),
                ('serial_number', models.CharField(max_length=40)),
                ('model', models.CharField(max_length=10)),
                ('company', models.CharField(max_length=50)),
            ],
        ),
    ]
