# Generated by Django 4.1.3 on 2022-12-11 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_remove_asset_id_alter_asset_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='image_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
