# Generated by Django 4.1.3 on 2022-12-11 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0003_asset_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='model',
            field=models.CharField(max_length=20),
        ),
    ]
