# Generated by Django 4.1.3 on 2022-12-16 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0005_asset_status_alter_asset_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
